CREATE OR REPLACE PROCEDURE INSERTA IS
    BEGIN
        INSERT INTO AREA VALUES ('MAT','Matematicas');
    END;
/

CREATE OR REPLACE PROCEDURE INSERTA 
    (
        CODIGO IN AREA.ID_MATERIA%TYPE,
        DESCRIPCION IN AREA.DESCRIPCION_MATERIA%TYPE
    )
    IS
    BEGIN
        INSERT INTO AREA VALUES (CODIGO, DESCRIPCION);
    END;
/

SELECT * FROM AREA;

EXECUTE INSERTA ('FIL','Filosofia')
EXECUTE INSERTA ('MUS','Musica')
EXECUTE INSERTA ('CC','Ciencias de la computacion')
EXECUTE INSERTA ('ING','Ingles clasico')